$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Schema for user-provided configuration files."
type: object
additionalProperties: false
properties:
  tiny_files:
    type: boolean
    description: "If True, use smaller, clipped files for processing. If False, use full global datasets."

  buffer_crs:
    type: string
    description: "CRS for buffering shapes. Use 'UTM' for UTM zones or 'epsg:xxxx' for a specific CRS."

  split_by:
    type: string
    description: "Field to split the input shapes by, e.g., 'country_id'."

  land_cover_types:
    type: object
    additionalProperties:
      type: string
    description: "Mapping of land cover types to their categories."

  techs:
    type: object
    additionalProperties:
      type: object
      properties:
        initial_area:
          type: string
          enum: ["settlement_area", "pixel_area"]
        continuous_layers:
          type: object
          additionalProperties:
            type: object
            properties:
              min:
                type: number
              max:
                type: number
            required: ["min", "max"]
        binary_layers:
          type: object
          additionalProperties:
            type: number
        shapes_buffer:
          type: object
        density:
          type: number
          description: "Density of renewable technology in MW/km2."
        lifetime:
          type: number
        costs:
          type: object
          properties:
            CAPEX:
              type: number
              description: "Upfront cost in EUR/MW."
            OPEX:
              type: number
              description: "Fixed operational cost in EUR/MW."
            WACC:
              type: number
              description: "Weighted average cost of capital."
          required: ["CAPEX", "OPEX", "WACC"]
          additionalProperties: false
      required: ["initial_area", "continuous_layers", "binary_layers"]
      additionalProperties: false
    

  overrides:
    type: object
    additionalProperties: true
      # properties:
  
  land_cost_curve_tech:
    type: string
  
  land_share_type:
    type: number

  min_protected_share:
    type: number