$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Schema for user-provided configuration files."
type: object
additionalProperties: false
properties:
  tiny_files:
    type: boolean
    description: "If True, use smaller, clipped files for processing. If False, use full global datasets."

  buffer_crs:
    type: string
    description: "CRS for buffering shapes. Use 'UTM' for UTM zones or 'epsg:xxxx' for a specific CRS."

  split_by:
    type: string
    description: "Field to split the input shapes by, e.g., 'country_id'."

  land_cover_types:
    type: object
    additionalProperties:
      type: string
    description: "Mapping of land cover types to their categories."

  techs:
    type: object
    additionalProperties:
      type: object
      properties:
        initial_area:
          type: string
          enum: ["settlement_area", "pixel_area"]
        continuous_layers:
          type: object
          additionalProperties:
            type: object
            properties:
              min:
                type: number
              max:
                type: number
            required: ["min", "max"]
        binary_layers:
          type: object
          additionalProperties:
            type: number
        shapes_buffer:
          type: object
      required: ["initial_area", "continuous_layers", "binary_layers"]
      additionalProperties: false
    density:
      type: float
      description: "Density of renewable technology in MW/km2."
    cost:
      CAPEX:
        type: float
      OPEX:
        type: float
      WACC:
        type: float

  overrides:
    type: object
    additionalProperties:
      type: object
