# Module settings that users cannot modify.
resources:
  automatic:
    ##
    # Links for automatically downloaded files
    ##
    slope: "https://zenodo.org/records/14920379/files/slope.in.degree_edtm_m_240m_s_20000101_20221231_go_epsg.4326_v20241230.tif"
    bathymetry: "https://zenodo.org/records/15741950/files/gebco_2024_sub_ice_cog.tif"
    globcover: "https://due.esrin.esa.int/files/Globcover2009_V2.3_Global_.zip"
    globcover_landcover_tif: "GLOBCOVER_L4_200901_200912_V2.3.tif"
    ghsl: "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_BUILT_S_GLOBE_R2023A/GHS_BUILT_S_E2025_GLOBE_R2023A_4326_30ss/V1-0/GHS_BUILT_S_E2025_GLOBE_R2023A_4326_30ss_V1_0.zip"
    ghsl_tif: "GHS_BUILT_S_E2025_GLOBE_R2023A_4326_30ss_V1_0.tif"
    solar_atlas: "https://worldbank-atlas.s3.us-east-1.amazonaws.com/download/World/World_PVOUT_GISdata_LTAy_AvgDailyTotals_GlobalSolarAtlas-v2_GEOTIFF.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAS2HACIWTA2CBBMO7%2F20251211%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20251211T085249Z&X-Amz-Expires=900&X-Amz-Security-Token=IQoJb3JpZ2luX2VjECAaCWV1LXdlc3QtMSJGMEQCIGBKjUDCRdIQznuubnAZSG3iGA1jpY8I3CeYYOLtIiLCAiBtmgIyuettflK%2FWOERJh8jCIUefkpUVBm%2F0JpL9tZQVCreAwjp%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAQaDDE5Mzc0MzQzOTI3MCIMJ5YQyMFNrOLA4Q8CKrIDXXkaLRT%2FKcIiSV3AkF%2FFibgeCxMpadbxKyx0BGEutPHlbE1vpDkD2LxlduqjoLGFjenK5uGCatImla3b85ePitCy0P9STmpXHKMlQYjMn3HtYU9OEsnIkf4PhH5A2dLn7ArOA9Ia6hYenyFzZ2r9xDcf%2F0cHRp3xQGXG1d7RjZm4AvhoRvpwfu0%2Bxrii%2FFYjKrP1qtgobMWKfs68%2FoFv0f5Eh%2BLaq7AWBeMeszksbWluVPg7ANrPzoQOjIeiMGwQGn2gElH1S%2F5ruN1o6XdKS4Ih%2BdiMChdEL73iNPLcOw81M%2BiHsPC4dSyuM%2B1WoUlhTl4vZDRypIiU9YCJs2gqQ%2B9w0NE6caYqfrWnGjgoZHaUh0Isssb17Y63f2RUSp%2BJpCPtJQQtxvuMRc%2FMptXvk41aWJeLismrn%2FK8do4BZ%2B%2BC1EyY06YUSlkQV8D%2FVvduSe1OLZIWE9MY70QAtXBHWcUXteWVbX%2F0nRCiqCtnc4TiVCKzu3lD%2Bi5cQZXK%2B8EOydnBI%2BUuudRL%2BeMXnD0bhr2VZkmQvuXvHLseHdSwiTuB33Wjpm%2Bkkau5iqJ%2FzpzOgtYw4vfpyQY6nwF%2FntGqs%2F0T1GzGGrQfncugDHqYHYW55LwXVj53mSA%2FzEaCwJZLkuwwyAl1sHqhqxZ%2Bgg%2F386zQl6vLEQYX6kiA%2B9PlI1LFoZg0xqmdaLycgFWcGICOTGD4M4nYCfiYlb8%2FGRBpsBPtbJ0NcVJUVLwWHZpzF1kgsBKTp7SkZxV0FP4d3giY%2FBRUvNxFd9fVWE85bZVq%2F8n2Fb90LFa27yM%3D&X-Amz-Signature=f195f77ee40509b0942f07f157299d2ba0ec96d3ea4dab3e4a7418def5f961e8&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject"
    solar_atlas_tif: "World_PVOUT_GISdata_LTAy_AvgDailyTotals_GlobalSolarAtlas-v2_GEOTIFF/PVOUT.tif"
    wind_atlas: "https://globalwindatlas.info/api/gis/global/capacity-factor_IEC1/"

land_cover_types:
  POST_FLOODING: FARM
  RAINFED_CROPLANDS: FARM
  MOSAIC_CROPLAND: FARM
  MOSAIC_VEGETATION: FOREST # According to the documentation, this is 50-70% grassland/shrubland/forest, and 25-50% cropland (https://due.esrin.esa.int/files/GLOBCOVER2009_Validation_Report_2.2.pdf)
  CLOSED_TO_OPEN_BROADLEAVED_FOREST: FOREST
  CLOSED_BROADLEAVED_FOREST: FOREST
  OPEN_BROADLEAVED_FOREST: FOREST
  CLOSED_NEEDLELEAVED_FOREST: FOREST
  OPEN_NEEDLELEAVED_FOREST: FOREST
  CLOSED_TO_OPEN_MIXED_FOREST: FOREST
  MOSAIC_FOREST: FOREST
  CLOSED_TO_OPEN_REGULARLY_FLOODED_FOREST: FOREST
  CLOSED_REGULARLY_FLOODED_FOREST: FOREST
  MOSAIC_GRASSLAND: GRASS
  CLOSED_TO_OPEN_SHRUBLAND: SHRUB
  CLOSED_TO_OPEN_HERBS: GRASS
  SPARSE_VEGETATION: BARE
  CLOSED_TO_OPEN_REGULARLY_FLOODED_GRASSLAND: GRASS
  BARE_AREAS: BARE
  ARTIFICIAL_SURFACES_AND_URBAN_AREAS: URBAN
  WATER_BODIES: WATER
  PERMANENT_SNOW: NOT_SUITABLE
  NO_DATA: NOT_SUITABLE
