# Options for buffering: either a string of the form "epsg:xxxx" or "UTM"/"utm"
# - "UTM": project each shape to the UTM zone of its centroid for buffering
# - "epsg:xxxx": use the specified CRS for all buffering
#   A good option is "epsg:8857" (WGS 84 / Equal Earth Greenwich) for global coverage
buffer_crs: "epsg:8857"

split_by: country_id  # likely country_id or shape_id

# Optional - specify land_cover_types here to override the internal defaults.

techs:
  pv_rooftop:
    initial_area: settlement_area
    continuous_layers:
      settlement_share:
        min: 0.01
        max: 1
        share: 0.8
    binary_layers:
      regions_maritime: 0
      regions_land: 1
      protected: 0
      # Include all land cover types; selection is done by settlement_share
      landcover_FARM: 1
      landcover_FOREST: 1
      landcover_URBAN: 1
      landcover_OTHER: 1
      landcover_NOT_SUITABLE: 0
      landcover_WATER: 0
    density: 5
    lifetime: 20
    costs: # TODO: this needs to be country-specific
      CAPEX: 505000
      OPEX: 7900
      WACC: 0.04
      # TODO: the current OPEX is FOM, need to add variable OM?
  pv_open_field:
    initial_area: pixel_area
    continuous_layers:
      slope:
        min: 0
        max: 3
      settlement_share:
        min: 0
        max: 0.01
    binary_layers:
      regions_maritime: 0
      regions_land: 1
      protected: 0
      landcover_FARM: 0.1
      landcover_FOREST: 0
      landcover_URBAN: 0
      landcover_OTHER: 0.2
      landcover_NOT_SUITABLE: 0
      landcover_WATER: 0
    density: 10
    lifetime: 20
    costs: # TODO: this needs to be country-specific
      CAPEX: 240000
      OPEX: 5000
      WACC: 0.08
  wind_onshore:
    initial_area: pixel_area
    continuous_layers:
      slope:
        min: 0
        max: 20
      settlement_share:
        min: 0
        max: 0.01
    binary_layers:
      regions_maritime: 0
      regions_land: 1
      protected: 0
      landcover_FARM: 0.2
      landcover_FOREST: 0.05
      landcover_URBAN: 0
      landcover_OTHER: 0.3
      landcover_NOT_SUITABLE: 0
      landcover_WATER: 0
    density: 5
    lifetime: 30
    costs: # TODO: this needs to be country-specific
      CAPEX: 960000
      OPEX: 11340
      WACC: 0.08
  wind_offshore:
    initial_area: pixel_area
    continuous_layers:
      bathymetry:
        min: -50
        max: 0
        share: 0.8
    binary_layers:
      regions_land: 0
      regions_maritime: 1
      protected: 0
    shapes_buffer:
      land: 10000  # meters
    density: 15
    lifetime: 30
    costs: # TODO: this needs to be country-specific
      CAPEX: 1680000
      OPEX: 32493
      WACC: 0.1

# Optional: override settings for specific subunits (countries, regions, etc.)
# This allows you to set specific parameters that differ from the defaults,
# or apply settings that are not defined in the defaults (defaults = `techs` section).
# The subunit keys should match the subunit IDs used in column selected in `split_by`.
overrides:
  PRT:  # Inside a subunit, any setting from `techs` can be overridden
    wind_offshore:
      shapes_buffer:
        land: 2000  # meters
  NLD:
    wind_offshore:
      shapes_buffer:
        land: 22000  # 22 km = 12 nautical miles

land_cost_curve_tech: wind_onshore

land_share_type: 0.5
